name: Deploy Portal Bot to Raspberry Pi 5

on:
   workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Publish
        run: |
          dotnet publish -c Release -o output

      - name: Stop Old Bot Instance
        run: |
          sudo systemctl stop portal-bot || true

      - name: Deploy Bot
        run: |
          sudo cp -r output /home/firesteel/Bots/Portal/

      - name: Pass Discord Bot Token
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: | # Create environment file for the bot to access discord token
          echo "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}" | sudo tee /home/firesteel/Bots/Portal/.env > /dev/null
          
      - name: Start Service
        run: sudo systemctl start portal-bot

      - name: Enable Service to Start on Boot
        run: sudo systemctl enable portal-bot
