name: Deploy Portal Bot to Raspberry Pi 5

on: # Trigger when a pull request or commit has been pushed to the "production" branch
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  request-approval: # Request approval before deploying
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: request-approval
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build and Publish
        run: |
          dotnet publish -c Release -o output

      - name: Stop Old Bot Instance
        run: |
          sudo systemctl stop portal-bot || true

      - name: Deploy Bot
        run: |
          sudo cp -r output /home/firesteel/Bots/Portal/
          sudo systemctl start portal-bot

      - name: Deploy Bot
        run: |
          sudo cp -r output /home/firesteel/Bots/Portal/

      - name: Pass Discord Bot Token
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: | # Create environment file for the bot to access discord token
          echo "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}" | sudo tee /home/firesteel/Bots/Portal/.env > /dev/null
          
      - name: Start Service
        run: sudo systemctl start portal-bot

      - name: Enable Service to Start on Boot
        run: sudo systemctl enable portal-bot
